name: Cargo CI/CD Pipeline

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  
          cache: 'npm'      

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript type checking
        run: npm run typescript:check

      

    # - name: Run tests
    #   run: npm test

    # - name: Build Expo web
    #   run: npm run build:web 
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build-and-test  
  #   if: github.ref == 'refs/heads/main'  

  #   steps:
  #     # Checkout the code
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     # Set up Node.js
  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 18
  #         cache: 'npm'

  #     # Install dependencies
  #     - name: Install dependencies
  #       run: npm install

  #     # Build the project
  #     - name: Build project
  #       run: npm run build

  #     # Deploy to your server (example using SSH)
  #     - name: Deploy to server
  #       uses: appleboy/ssh-action@v1
  #       with:
  #         host: ${{ secrets.SSH_HOST }}  # Add your server's IP/hostname in GitHub Secrets
  #         username: ${{ secrets.SSH_USERNAME }}  # Add your SSH username in GitHub Secrets
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}  # Add your SSH private key in GitHub Secrets
  #         script: |
  #           cd /path/to/your/project  # Change to your project directory on the server
  #           git pull origin main      # Pull the latest changes
  #           npm install               # Install dependencies
  #           npm run build             # Build the project
  #           pm2 restart all           # Restart your Node.js application (if using PM2)